apiVersion: apps/v1
kind: Deployment
metadata: 
  name: custom-web
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - name: webapp
          image: jabin95/nginx-custom-container:01
          ports:
           - containerPort: 80   
---

apiVersion: v1
kind: Service
metadata:
  name: service-webapp
spec:
  selector:
    app: webapp
  ports:
    - name: tcp
      port: 80
      targetPort: 80
  type: NodePort
